name: 'submit action'
description: 'submits a package to the package database'

inputs:
  dispatch-token:
    description: token required for dispatch
    required: true
  dispatch-target:
    description: repository managing your packages
    required: true
  branch:
    description: manjaro branch to publish against
    required: false
    default: "stable"
  
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@main
    - name: determine versions
      shell: bash
      run: |
        echo ${{ github.token }} | gh auth login --with-token
        release="$(gh release list --limit 3 | grep "^${{ inputs.branch }}" | head -1 | awk '{print $1;}')"
        echo "release=${release}" >> $GITHUB_ENV
    - name: dispatch
      if: ${{ inputs.dispatch-token != '' && inputs.dispatch-target != '' }}
      uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3
      with:
        token: ${{ inputs.dispatch-token }}
        repository: ${{ inputs.dispatch-target }}
        event-type: package_update
        client-payload: '{ "repository": "${{ github.repository }}", "release": "${{ env.release }}", "branch": "${{ inputs.branch }}" }'
